-- Run this in Supabase SQL Editor before connecting the shared version.
create table if not exists public.members (id uuid primary key default gen_random_uuid(), name text not null, phone text not null, active boolean not null default true, created_at timestamptz not null default now());
alter table public.members add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.members add column if not exists email text;
create unique index if not exists members_user_id_key on public.members(user_id) where user_id is not null;
create unique index if not exists members_email_key on public.members(lower(email)) where email is not null;
create table if not exists public.loans (id uuid primary key default gen_random_uuid(), member_id uuid not null references public.members(id), principal numeric(12, 2) not null check (principal > 0), loan_date date not null default current_date, created_at timestamptz not null default now());
alter table public.loans add column if not exists eligible_limit numeric(12, 2);
create table if not exists public.payments (id uuid primary key default gen_random_uuid(), loan_id uuid not null references public.loans(id), amount numeric(12, 2) not null check (amount > 0), payment_type text not null default 'auto' check (payment_type in ('interest', 'principal', 'auto')), payment_date date not null default current_date, created_at timestamptz not null default now());
alter table public.payments add column if not exists payment_type text not null default 'auto';
alter table public.payments drop constraint if exists payments_payment_type_check;
alter table public.payments add constraint payments_payment_type_check check (payment_type in ('interest', 'principal', 'auto'));
create table if not exists public.contributions (id uuid primary key default gen_random_uuid(), member_id uuid references public.members(id), amount numeric(12, 2) not null check (amount > 0), contribution_date date not null default current_date, note text, created_at timestamptz not null default now());
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, role text not null default 'member' check (role in ('admin', 'member')), created_at timestamptz not null default now());
alter table public.members enable row level security;
alter table public.loans enable row level security;
alter table public.payments enable row level security;
alter table public.contributions enable row level security;
alter table public.profiles enable row level security;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;
drop policy if exists "authenticated users can read members" on public.members;
drop policy if exists "authenticated users can read loans" on public.loans;
drop policy if exists "authenticated users can read payments" on public.payments;
drop policy if exists "authenticated users can read contributions" on public.contributions;
drop policy if exists "authenticated users can read profiles" on public.profiles;
drop policy if exists "approved users can read members" on public.members;
drop policy if exists "approved users can read loans" on public.loans;
drop policy if exists "approved users can read payments" on public.payments;
drop policy if exists "approved users can read contributions" on public.contributions;
drop policy if exists "admins can manage members" on public.members;
drop policy if exists "admins can manage loans" on public.loans;
drop policy if exists "admins can manage payments" on public.payments;
drop policy if exists "admins can manage contributions" on public.contributions;
drop policy if exists "users can read own profile" on public.profiles;
create policy "approved users can read members" on public.members for select to authenticated using (exists (select 1 from public.profiles where id = auth.uid()));
create policy "admins can manage members" on public.members for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "approved users can read loans" on public.loans for select to authenticated using (exists (select 1 from public.profiles where id = auth.uid()));
create policy "admins can manage loans" on public.loans for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "approved users can read payments" on public.payments for select to authenticated using (exists (select 1 from public.profiles where id = auth.uid()));
create policy "admins can manage payments" on public.payments for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "approved users can read contributions" on public.contributions for select to authenticated using (exists (select 1 from public.profiles where id = auth.uid()));
create policy "admins can manage contributions" on public.contributions for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "users can read own profile" on public.profiles for select to authenticated using (id = auth.uid());
do $$ begin alter publication supabase_realtime add table public.members; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.loans; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.payments; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.contributions; exception when duplicate_object then null; end $$;